#!/usr/bin/env python2.7
# -*- Mode: Python; tab-width: 4; py-indent-offset: 4; -*-

#
# CLI interface to ytdrep.py - dumps .xlsx summary of specified
# year to stdout.
#

import sys
from dbtools import getdb
from ytdrep import ytd_rep_stream

if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.stderr.write('usage: %s year\n' % sys.argv[0])
        sys.exit(1)
        
    db = getdb()
    year = '%04d' % int(sys.argv[1])
    h = ytd_rep_stream(db, year)
    while 1:
        x = h.read()
        if not x:
            break
        sys.stdout.write(x)
    h.close()
